
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class CustomerLogin extends javax.swing.JFrame implements objects {
      public  String email;
      public String Password;
    /**
     * Creates new form CustomerLogin
     */
    public CustomerLogin() {
        initComponents();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
   
     public void close(){
       WindowEvent closing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closing);
       
   }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfemail = new javax.swing.JTextArea();
        Registerbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpeg (1).jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        passwordtxt.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(162, 118, 141));
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        jPanel1.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 180, 30));

        jScrollPane4.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tfemail.setColumns(20);
        tfemail.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        tfemail.setForeground(new java.awt.Color(162, 118, 141));
        tfemail.setRows(5);
        jScrollPane4.setViewportView(tfemail);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 180, 30));

        Registerbtn.setBackground(new java.awt.Color(204, 204, 204));
        Registerbtn.setFont(new java.awt.Font("Sitka Small", 0, 15)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(162, 118, 141));
        Registerbtn.setText("Don't have an account? Signup Here");
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 320, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        LoginBtn.setBackground(new java.awt.Color(204, 204, 204));
        LoginBtn.setFont(new java.awt.Font("Sitka Small", 0, 20)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(162, 118, 141));
        LoginBtn.setText("LOGIN");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 180, 40));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back.setForeground(new java.awt.Color(162, 118, 141));
        back.setText("←");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpeg (1).jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed

    }//GEN-LAST:event_passwordtxtActionPerformed

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
dispose();
Register r1=new Register();
r1.setLocationRelativeTo(null);
r1.setVisible(true);      
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:

        String name;
        email = tfemail.getText();
        Password = passwordtxt.getText();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con= DriverManager.getConnection("jdbc:ucanaccess://E:/Data Structures Ms Aleenah/DSPORJECTCODE/DSPROJECT/AirplaneDatabase1.accdb");
          //  con= DriverManager.getConnection("jdbc:ucanaccess://C:/Users/Dell/Documents/Downloads/DSPROJECT/DSPROJECT/AirplaneDatabase1.accdb");
       //Tooba     //con= DriverManager.getConnection("jdbc:ucanaccess://C:/Users/HP/Downloads/DSPROJECT/AirplaneDatabase1.accdb");
       //Noor     //con= DriverManager.getConnection("jdbc:ucanaccess://C:/Users/Dell/Documents/Downloads/DSPROJECT NEW/DSPROJECT (1)/DSPROJECT/AirplaneDatabase1.accdb");
            pst= con.prepareStatement("Select * from UserInformation where Email='"+email+"' and Password='"+Password+"'");
            rs=pst.executeQuery();
            if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Successfully signed in");
                   
                    dispose();
                    name = rs.getString("Name");
                    f1.jLabel1.setText("Welcome to TripAdvisor "+name+"!");
                   // f3.details(tfemail.toString());
                   f1.setEmailPw(email, Password);
                    rs.close();
                    pst.close();
                    
                    f1.setLocationRelativeTo(null);
                    f1.setVisible(true);
                              
                }  
                else{
                JOptionPane.showMessageDialog(this, "Incorrect Email ID/Password");
                }
            
            tfemail.setText("");
            passwordtxt.setText("");
            tfemail.requestFocus();
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerLogin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(CustomerLogin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        AdminCustomer ac=new AdminCustomer();
        ac.setLocationRelativeTo(null);
        ac.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton Registerbtn;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    protected javax.swing.JPasswordField passwordtxt;
    protected javax.swing.JTextArea tfemail;
    // End of variables declaration//GEN-END:variables
}
