
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class Register extends javax.swing.JFrame implements objects {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    public void close(){
       WindowEvent closing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closing);
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        emailtxt = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        usercnictxt = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        userpwtxt = new javax.swing.JPasswordField();
        registerbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Usernametxt = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        usernumbertxt = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 490));
        setPreferredSize(new java.awt.Dimension(650, 460));

        jPanel1.setMaximumSize(new java.awt.Dimension(678, 452));
        jPanel1.setPreferredSize(new java.awt.Dimension(678, 452));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTERATION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CNIC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile Number:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jScrollPane4.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        emailtxt.setColumns(20);
        emailtxt.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(162, 118, 141));
        emailtxt.setRows(5);
        jScrollPane4.setViewportView(emailtxt);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 180, 30));

        jScrollPane5.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setToolTipText("");
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        usercnictxt.setColumns(20);
        usercnictxt.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        usercnictxt.setForeground(new java.awt.Color(162, 118, 141));
        usercnictxt.setRows(5);
        usercnictxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usercnictxtKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(usercnictxt);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 180, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        userpwtxt.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        userpwtxt.setForeground(new java.awt.Color(162, 118, 141));
        userpwtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpwtxtActionPerformed(evt);
            }
        });
        jPanel1.add(userpwtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 180, 30));

        registerbtn.setBackground(new java.awt.Color(204, 204, 204));
        registerbtn.setFont(new java.awt.Font("Sitka Small", 0, 20)); // NOI18N
        registerbtn.setForeground(new java.awt.Color(162, 118, 141));
        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 160, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jScrollPane6.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setToolTipText("");
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Usernametxt.setColumns(20);
        Usernametxt.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        Usernametxt.setForeground(new java.awt.Color(162, 118, 141));
        Usernametxt.setRows(5);
        jScrollPane6.setViewportView(Usernametxt);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 180, 30));

        jScrollPane7.setForeground(new java.awt.Color(221, 161, 80));
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setToolTipText("");
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        usernumbertxt.setColumns(20);
        usernumbertxt.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        usernumbertxt.setForeground(new java.awt.Color(162, 118, 141));
        usernumbertxt.setRows(5);
        usernumbertxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernumbertxtKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(usernumbertxt);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 180, 30));

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        back.setForeground(new java.awt.Color(162, 118, 141));
        back.setText("←");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpeg (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userpwtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpwtxtActionPerformed

    }//GEN-LAST:event_userpwtxtActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
             // TODO add your handling code here:
             String Name;
             String pass;
             String email;
             String cnic;
             String phonenumber;
             Name = Usernametxt.getText();
             pass = userpwtxt.getText();
             email = emailtxt.getText();
             cnic = usercnictxt.getText();
             phonenumber = usernumbertxt.getText();
             try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con= DriverManager.getConnection("jdbc:ucanaccess://E:/Data Structures Ms Aleenah/DSPORJECTCODE/DSPROJECT/AirplaneDatabase1.accdb");
          //  con= DriverManager.getConnection("jdbc:ucanaccess://C:/Users/Dell/Documents/Downloads/DSPROJECT/DSPROJECT/AirplaneDatabase1.accdb");
            pst=con.prepareStatement("insert into UserInformation(Number,Name,Password,Email,CNIC)values(?,?,?,?,?)");
            pst.setString(1, phonenumber);
            pst.setString(2, Name);
            pst.setString(3, pass);
            pst.setString(4, email);
            pst.setString(5, cnic);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Account created");
            f1.jLabel1.setText("Welcome to TripAdvisor "+Name+"!");
            Usernametxt.setText("");
            usercnictxt.setText("");
            usernumbertxt.setText("");
            userpwtxt.setText("");
            emailtxt.setText("");
           
            dispose();
            cl.setLocationRelativeTo(null);
            cl.setVisible(true);
            
            
        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }       
                                            

                     
    }//GEN-LAST:event_registerbtnActionPerformed

    private void usernumbertxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernumbertxtKeyTyped
 char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        
    }//GEN-LAST:event_usernumbertxtKeyTyped

    private void usercnictxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usercnictxtKeyTyped
char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)) {
            evt.consume();
        }        
       
    }//GEN-LAST:event_usercnictxtKeyTyped

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        cl.setLocationRelativeTo(null);
        cl.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Usernametxt;
    private javax.swing.JButton back;
    private javax.swing.JTextArea emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextArea usercnictxt;
    private javax.swing.JTextArea usernumbertxt;
    private javax.swing.JPasswordField userpwtxt;
    // End of variables declaration//GEN-END:variables
}
